version: "3.8"
services:
  app:
    restart: always
    build:
      context: ./application
    image: lungspot:1.0
    container_name: uwsgi_app
    volumes:
      - ./application:/app
      - ./sockets:/sockets
    command: uwsgi /app/uwsgi.ini
  
  nginx:
    build: ./nginx
    restart: always
    container_name: nginx_server
    volumes:
      - ./sockets:/sockets
      - ./application/lungspot_django/media:/media
    ports:
      - 80:80
    depends_on:
      - app
